### PR TITLE
add initialSourceIndexPath and finalDestinationIndexPath

### PR DESCRIPTION
**Pull request by RickeyBoy**
When I intent to send a urlRequest that inform back-end the changes of model, I found that I can only do this in `tableview(_:reorderRowAt:to)`.
However this means that during the Drag&Drop I have to send lots of urlRequest which is not necessary.
So I added two properties to help. 
Usage:

> func tableViewDidFinishReordering(_ tableView: UITableView) {
>         guard let rowS = tableView.reorder.initialSourceIndexPath?.row,
>             let rowD = tableView.reorder.finalDestinationIndexPath?.row else { return }
>         print("move \(rowS) to \(rowD)")
>     }

(This is my first pull request. Hope you don't mind if I make some mistakes. )

### CODE REVIEW

**Comment by adamshin** [comment]
Hey, thanks for contributing. This could definitely be useful.

I think `initialSourceIndexPath` and `finalDestinationIndexPath` might make more sense as parameters to the `tableViewDidFinishReordering` delegate method. That way there's no mutable state & no need to unwrap optionals. What are your thoughts?

**Comment by RickeyBoy** [comment]
Yeah, I think you're right. And I changed `initialSourceIndexPath` and `finalDestinationIndexPath`  to `private`.

Usage now becomes:
> func tableViewDidFinishReordering(_ tableView: UITableView, initSource: IndexPath, finalDestination: IndexPath) {
>         print("\(initSource) to \(finalDestination)")
>     }

**Comment by adamshin** [comment]
You should be able to remove the `initialSourceIndexPath` and `finalDestinationIndexPath` properties altogether - both those values are available in the ReorderState.reordering case. We're unpacking the destination indexpath at the beginning of endReorder(), and we can access the source indexpath the same way. Currently that value's just being ignored.

**Comment by RickeyBoy** [comment]
I've removed those two properties in the way you said. Hope it works well now :)

**Comment by adamshin** [comment]
Looks good thanks!

One last thought: can you change the parameter names in that delegate method to

`tableViewDidFinishReordering(_ tableView: UITableView, from initialSourceIndexPath: IndexPath, to finalDestinationIndexPath: IndexPath)`?

A little more verbose, but consistent with the other methods.

**Comment by RickeyBoy** [comment]
All done! Really appreciate your patience and efforts- definitely made my first contributing experience an amazing one! Looking forward to cooperation in the future :)

**Pull request merged**
